# Generated by Django 5.2.4 on 2025-07-26 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('ready', 'Готов к доставке'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн оплата')], max_length=20, verbose_name='Способ оплаты')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии к заказу')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=200, verbose_name='Надпись')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('notes', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('selected_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='Выбранный цвет')),
                ('selected_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='Выбранный размер')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
    ]
