# Generated by Django 4.2.23 on 2025-07-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_size',
        ),
    ]
