# Generated by Django 4.2.23 on 2025-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_source_remove_product_sizes_delete_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите основное изображение товара', null=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.CharField(choices=[('wedding', 'Свадьба'), ('corporate', 'Корпоратив'), ('graduation', 'Выпускной'), ('anniversary', 'Годовщина'), ('baby_shower', 'Рождение ребенка'), ('valentine', 'День святого Валентина'), ('new_year', 'Новый год'), ('other', 'Другое')], max_length=20, verbose_name='Тематика'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
