# Generated by Django 4.2.23 on 2025-07-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_review_product_rename_colors_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
